"""
tests/test_anomalies.py – tests for crumb.anomalies module.

Uses the synthetic sample data to verify the spec-required anomaly dates are
flagged (2026-06-09 closure, 2026-07-18/19 promo spike, 2026-08-10–12 slow).
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from crumb.anomalies import find_anomalies, find_possible_closures

# ---------------------------------------------------------------------------
# Fixtures using the real sample data (generated by gen_sample_data.py)
# ---------------------------------------------------------------------------
_SAMPLE_CSV = Path(__file__).parent.parent / "data" / "sample_bakery_sales.csv"


@pytest.fixture(scope="module")
def sample_df():
    if not _SAMPLE_CSV.exists():
        pytest.skip("sample_bakery_sales.csv not generated yet")
    from crumb.data import load_csv
    df, _ = load_csv(str(_SAMPLE_CSV))
    return df


# ---------------------------------------------------------------------------
# Closure detection
# ---------------------------------------------------------------------------
def test_closure_date_detected(sample_df):
    closures = find_possible_closures(sample_df)
    assert "2026-06-09" in closures, f"Expected 2026-06-09 in closures, got: {closures}"


# ---------------------------------------------------------------------------
# Promo spike detection
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("item", ["Croissant", "Espresso", "Cinnamon Roll"])
@pytest.mark.parametrize("spike_date", ["2026-07-18", "2026-07-19"])
def test_promo_spike_detected(sample_df, item, spike_date):
    anomalies = find_anomalies(sample_df, item)
    dates = [a.date for a in anomalies]
    assert spike_date in dates, (
        f"Expected {spike_date} anomaly for {item}, got: {dates}"
    )
    # The direction should be "above" for a promo spike
    matching = [a for a in anomalies if a.date == spike_date]
    assert any(a.direction == "above" for a in matching)


# ---------------------------------------------------------------------------
# Slow-day detection
# ---------------------------------------------------------------------------
@pytest.mark.parametrize("item", ["Croissant", "Pain au chocolat"])
@pytest.mark.parametrize("slow_date", ["2026-08-10", "2026-08-11", "2026-08-12"])
def test_slow_days_detected(sample_df, item, slow_date):
    anomalies = find_anomalies(sample_df, item)
    dates = [a.date for a in anomalies]
    assert slow_date in dates, (
        f"Expected {slow_date} slow-day for {item}, got: {dates}"
    )
    matching = [a for a in anomalies if a.date == slow_date]
    assert any(a.direction == "below" for a in matching)


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------
def _make_simple_df(units_by_date: dict) -> pd.DataFrame:
    rows = []
    for date_str, units in units_by_date.items():
        d = pd.Timestamp(date_str)
        rows.append({
            "date": d, "item": "Bread", "units_sold": units,
            "day_of_week": d.dayofweek, "is_holiday": 0, "rainy": 0, "promo": 0,
        })
    return pd.DataFrame(rows)


def test_empty_item_returns_empty():
    df = _make_simple_df({"2026-01-05": 10})
    result = find_anomalies(df, "NonExistent")
    assert result == []


def test_no_anomalies_for_flat_series():
    """Perfectly flat series should produce no anomalies."""
    start = pd.Timestamp("2026-01-05")
    dates = [
        (start + pd.Timedelta(days=i)).strftime("%Y-%m-%d")
        for i in range(28)
    ]
    data = {d: 10.0 for d in dates}
    df = _make_simple_df(data)
    # Fill day_of_week properly
    df["day_of_week"] = df["date"].dt.dayofweek
    result = find_anomalies(df, "Bread")
    assert result == []


def test_anomaly_result_fields():
    """Verify AnomalyResult has all required fields."""
    dates = {}
    for i in range(35):
        d = pd.Timestamp("2026-01-05") + pd.Timedelta(days=i)
        if d.dayofweek == 6:
            continue
        v = 10.0 if d.date().isoformat() != "2026-01-26" else 100.0
        dates[d.strftime("%Y-%m-%d")] = v
    df = _make_simple_df(dates)
    df["day_of_week"] = df["date"].dt.dayofweek
    result = find_anomalies(df, "Bread")
    for a in result:
        assert hasattr(a, "date")
        assert hasattr(a, "actual")
        assert hasattr(a, "expected")
        assert hasattr(a, "pct_diff")
        assert hasattr(a, "direction")
        assert hasattr(a, "label")
        assert a.direction in ("above", "below")
